<?php
/**
 * Template Name: Custom Template
 *
 * A custom template framework for creating pages with wholly arbitrary layouts.
 * DO NOT EDIT THIS FILE. Instead, use the thesis_hook_custom_template() hook
 * to specify the contents of div#content_box. Be sure specify which page should
 * receive which code by dividing your action using the is_page() conditional tag.
 *
 * @package Thesis
 */

thesis_html_framework();